User.create(name: '勇人', password: 'password')
User.create(name: '慎太郎', password: 'password')
User.create(name: '優子', password: 'password')
User.create(name: '拓也', password: 'password')
User.create(name: '亮', password: 'password')
Room.create!(name:  "FCバイエルン・ミュンヘン　VS　ボルシア・ドルトムント")
Room.create!(name:  "アトレティコ・マドリード　VS　ユヴェントスFC")
Room.create!(name:  "マンチェスター・シティFC　VS　レアル・マドリード")
Room.create!(name:  "雑談部屋１")
Message.create!(content: 'ゴール！！', user_id: 1, room_id: 1)
Message.create!(content: 'ゴーーーーール！！', user_id: 2, room_id: 1)
Message.create!(content: '入れられたーーーー', user_id: 3, room_id: 1)
Message.create!(content: 'いいシュートだった！！', user_id: 4, room_id: 1)
Message.create!(content: '取り返せーー', user_id: 1, room_id: 1)
Message.create!(content: '負けるなー！がんばれー！', user_id: 5, room_id: 1)
Message.create!(content: '勝つぞー！！', user_id: 2, room_id: 1)
Message.create!(content: 'もうすぐキックオフ！', user_id: 1, room_id: 2)
Message.create!(content: '楽しみ！', user_id: 2, room_id: 2)
Message.create!(content: '勝ってくれー', user_id: 3, room_id: 2)
Message.create!(content: '楽しみ！', user_id: 4, room_id: 2)
Message.create!(content: 'サッカーファン集まれー！！！！！', user_id: 5, room_id: 4)